// Mocks generated by Mockito 5.4.6 from annotations
// in pet_finder_app/test/mocks/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pet_finder_app/core/networking/api_result.dart' as _i2;
import 'package:pet_finder_app/features/details/domain/repositories/derails_repository.dart'
    as _i6;
import 'package:pet_finder_app/features/home/domain/entities/breed.dart' as _i5;
import 'package:pet_finder_app/features/home/domain/repositories/breed_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BreedRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBreedRepository extends _i1.Mock implements _i3.BreedRepository {
  MockBreedRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<List<_i5.Breed>>> getBreeds({
    int? limit = 10,
    int? page = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBreeds, [], {#limit: limit, #page: page}),
            returnValue: _i4.Future<_i2.ApiResult<List<_i5.Breed>>>.value(
              _FakeApiResult_0<List<_i5.Breed>>(
                this,
                Invocation.method(#getBreeds, [], {#limit: limit, #page: page}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<_i5.Breed>>>);
}

/// A class which mocks [DetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailsRepository extends _i1.Mock implements _i6.DetailsRepository {
  MockDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i5.Breed>> getBreedDetails(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#getBreedDetails, [petId]),
            returnValue: _i4.Future<_i2.ApiResult<_i5.Breed>>.value(
              _FakeApiResult_0<_i5.Breed>(
                this,
                Invocation.method(#getBreedDetails, [petId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i5.Breed>>);
}
